-- Ensure default deck exists first
INSERT INTO mainichi_decks (id, author_id, title, description, is_premium)
VALUES (1, NULL, 'JLPT N5 Core', 'Master the essential kanji for the JLPT N5 exam.', FALSE)
ON DUPLICATE KEY UPDATE title = VALUES(title), description = VALUES(description);

DELETE FROM mainichi_vocabulary WHERE deck_id = 1;

INSERT INTO mainichi_vocabulary (deck_id, kanji, onyomi, kunyomi, english) VALUES 
(1, '先', 'セン', 'さき, ま.ず', 'ahead, before, future, precedence, previous'),
(1, '生', 'セイ, ショウ', 'い.きる, う.む, なま', 'birth, genuine, life'),
(1, '何', 'カ', 'なに, なん', 'what'),
(1, '一', 'イチ, イツ', 'ひと.つ', 'one'),
(1, '二', 'ニ', 'ふた.つ', 'two'),
(1, '三', 'サン', 'みっ.つ', 'three'),
(1, '四', 'シ', 'よ, よっ.つ, よん', 'four'),
(1, '五', 'ゴ', 'いつ.つ', 'five'),
(1, '六', 'ロク', 'むっ.つ', 'six'),
(1, '七', 'シチ', 'なな.つ', 'seven'),
(1, '八', 'ハチ', 'やっ.つ', 'eight'),
(1, '九', 'キュウ, ク', 'ここの.つ', 'nine'),
(1, '十', 'ジュウ', 'とお', 'ten'),
(1, '百', 'ヒャク', 'もも', 'hundred'),
(1, '千', 'セン', 'ち', 'thousand'),
(1, '万', 'マン, バン', 'よろず', 'ten thousand'),
(1, '円', 'エン', 'まる.い', 'circle, yen'),
(1, '日', 'ニチ, ジツ', 'ひ, か', 'day, sun, Japan'),
(1, '月', 'ゲツ, ガツ', 'つき', 'month, moon'),
(1, '火', 'カ', 'ひ, ほ', 'fire'),
(1, '水', 'スイ', 'みず', 'water'),
(1, '木', 'モク, ボク', 'き', 'tree, wood'),
(1, '金', 'キン, コン', 'かね, かな', 'gold, money'),
(1, '土', 'ド, ト', 'つち', 'earth, soil, ground'),
(1, '山', 'サン', 'やま', 'mountain'),
(1, '川', 'セン', 'かわ', 'river'),
(1, '天', 'テン', 'あめ, あま', 'heavens, sky'),
(1, '気', 'キ, ケ', 'いき', 'spirit, mind, air, atmosphere'),
(1, '雨', 'ウ', 'あめ', 'rain'),
(1, '人', 'ジン, ニン', 'ひと', 'person'),
(1, '女', 'ジョ', 'おんな, め', 'female, woman'),
(1, '男', 'ダン, ナン', 'おとこ', 'male, man'),
(1, '子', 'シ, ス', 'こ', 'child'),
(1, '父', 'フ', 'ちち', 'father'),
(1, '母', 'ボ', 'はは', 'mother'),
(1, '友', 'ユウ', 'とも', 'friend'),
(1, '本', 'ホン', 'もと', 'book, origin, main'),
(1, '学', 'ガク', 'まな.ぶ', 'study, learning, science'),
(1, '校', 'コウ', '', 'school, exam'),
(1, '名', 'メイ, ミョウ', 'な', 'name, reputation, distinguished'),
(1, '年', 'ネン', 'とし', 'year'),
(1, '大', 'ダイ, タイ', 'おお.きい', 'big, large, great'),
(1, '小', 'ショウ', 'ちい.さい, こ, お', 'small, little'),
(1, '中', 'チュウ', 'なか', 'middle, inside, center'),
(1, '高', 'コウ', 'たか.い', 'high, expensive, tall'),
(1, '長', 'チョウ', 'なが.い, おさ', 'long, leader, superior'),
(1, '半', 'ハン', 'なか.ば', 'half, middle, semi-'),
(1, '時', 'ジ', 'とき', 'time, hour'),
(1, '間', 'カン, ケン', 'あいだ, ま', 'interval, space, between'),
(1, '上', 'ジョウ', 'うえ, あ.がる, のぼ.る', 'above, up, over'),
(1, '下', 'カ, ゲ', 'した, さ.げる, くだ.る', 'below, down, under'),
(1, '前', 'ゼン', 'まえ', 'before, in front'),
(1, '後', 'ゴ, コウ', 'のち, うし.ろ, あと', 'after, behind, later'),
(1, '午', 'ゴ', 'うま', 'noon'),
(1, '今', 'コン, キン', 'いま', 'now'),
(1, '毎', 'マイ', 'ごと', 'every'),
(1, '行', 'コウ, ギョウ', 'い.く, おこな.う', 'go, conduct, line'),
(1, '来', 'ライ', 'く.る, きた.る', 'come, next, become'),
(1, '見', 'ケン', 'み.る, み.える, み.せる', 'see, look, visible'),
(1, '入', 'ニュウ', 'はい.る, い.れる', 'enter, insert'),
(1, '出', 'シュツ', 'で.る, だ.す', 'exit, leave, put out'),
(1, '読', 'ドク', 'よ.む', 'read'),
(1, '書', 'ショ', 'か.く', 'write'),
(1, '話', 'ワ', 'はな.す, はなし', 'talk, speech, story'),
(1, '聞', 'ブン, モン', 'き.く, き.こえる', 'hear, listen, ask'),
(1, '食', 'ショク', 'た.べる, く.う', 'eat, food'),
(1, '車', 'シャ', 'くるま', 'car, vehicle'),
(1, '語', 'ゴ', 'かた.る', 'language, word, speech'),
(1, '右', 'ウ, ユウ', 'みぎ', 'right'),
(1, '左', 'サ', 'ひだり', 'left'),
(1, '東', 'トウ', 'ひがし', 'east'),
(1, '西', 'セイ, サイ', 'にし', 'west'),
(1, '南', 'ナン', 'みなみ', 'south'),
(1, '北', 'ホク', 'きた', 'north'),
(1, '外', 'ガイ, ゲ', 'そと, ほか, はず.れる', 'outside, external'),
(1, '国', 'コク', 'くに', 'country, state'),
(1, '白', 'ハク, ビャク', 'しろ, しろ.い', 'white'),
(1, '電', 'デン', '', 'electricity'),
(1, '休', 'キュウ', 'やす.む', 'rest, day off'),
(1, '誰', 'スイ', 'だれ', 'who');